[Settings]
; 快捷键设置 (填入虚拟键码 Virtual-Key Code)
; 112=F1, 113=F2, 114=F3, 115=F4, 116=F5, 117=F6, 118=F7, 119=F8, 120=F9
HotKey=116


; 自动轮询的时间间隔 (单位：毫秒，1000 = 1秒)
; 建议不要低于 500，否则频繁读写硬盘可能导致游戏掉帧
PollInterval=2000

; 指定包含属性数据的 INI 文件名 (可以随时改成别人发给你的配置)
TargetINI=hotfix.ini

; 是否开启文件自动监控 (true=保存即生效，false=必须按热键生效)
AutoMonitor=true