[Settings]
; 自动监控开关。true: 保存目标 INI 文件即刻在游戏内生效；false: 需手动按热键触发
AutoMonitor=true

; 手动重载触发热键。默认 116 代表 F5 键 (采用 Windows 虚拟键码)
HotKey=116

; 调试控制台开关。true: 显示终端黑框以查看注入日志；false: 隐藏黑框
ShowConsole=false

; 目标监控文件列表。支持监控多个文件，用英文逗号分隔即可。这些文件需放在游戏根目录。
TargetINI=hotfix.ini,
